# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00ab84bd038f0512bd51d5e22bc662b08733e334871ce08df0840f5730596f703c11942c6fbf137cd05b2c99589c54c170340b9cd70aadb570002d43c7a0a0d4

test:
  secret_key_base: 77574004abcd2aa4b1dcd441085e594b7415a98eb2df0262b20f2895242922411dd69a0e7c2b9caf82379b71535ceaa3f34e8861af7f6c772de8e43463112ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
